### ISSUE TITLE
Replace synthetic alarms by generated sounds

### ISSUE THREAD

**Issue by thomas-mc-work** [qoomon/time-timer-webapp#47]
JavaScript has an API to generate arbitrary audio output. That would allow replacing the two alarm audio files by simple JavaScript.

Here is a nice introducing article about that topic: https://modernweb.com/audio-synthesis-javascript/

**Comment by qoomon** [comment]
Thanks for the information, but what is the benefit?

**Comment by thomas-mc-work** [comment]
Only that you can store the two alarms as code instead of the binary files

**Comment by qoomon** [comment]
Okay thanks for the hint, however I don't see the advantage.
